# BEGIN_KITTY_FONTS
font_family      family="JetBrainsMono Nerd Font Mono"
bold_font        auto
italic_font      family="Fira Code"
bold_italic_font auto
font_size 14
background_opacity .6

# [ Terminal options ] #
confirm_os_window_close 0
allow_remote_control yes
close_on_child_death no
listen_on unix:/tmp/mykitty
shell .
editor .


# [ Cursor options ] # 

# Potential Colors i liked: 
# #ffa700
# #ffd700
# #fabf4f
# #ffffff
# #3CBD41
# #EBA3FF
# #0059FF


cursor #E6A197
cursor_text_color #ffffff
cursor_shape beam

# [ Cursor trails ] #
cursor_trail 10
cursor_trail_start_threshold 0
cursor_trail_decay 0.1 0.4
cursor_blink true

# [ keybinds ] #

# navigation
map ctrl+k scroll_line_up
map ctrl+j scroll_line_down
map ctrl+shift+k scroll_page_up
map ctrl+shift+j scroll_page_down

map alt+l neighboring_window right
map alt+k neighboring_window up
map alt+j neighboring_window down
map alt+h neighboring_window left

# resizing

window_resize_step_lines 2
window_resize_step_cells 2

map alt+shift+l kitten relative_resize.py right 1
map alt+shift+k kitten relative_resize.py up    1
map alt+shift+h kitten relative_resize.py left  1
map alt+shift+j kitten relative_resize.py down  1

# windows
map alt+shift+q close_window 
map alt+' launch --location=hsplit --cwd=current 
map alt+shift+5 launch --location=vsplit --cwd=current
map alt+shift+' launch --location=vsplit --cwd=current
map alt+shift+m detach_window

map ctrl+alt+l move_window_forward
map ctrl+alt+h move_window_backward


map ctrl+shift+[ next_layout
map ctrl+shift+] next_layout

# tabs
map alt+t new_tab_with_cwd
map alt+shift+t new_tab 

map alt+tab next_tab
map alt+shift+tab previous_tab


# launch programs
map alt+e launch nvim
map alt+m launch spt
map alt+r load_config_file
map alt+shift+r set_tab_title
map alt+c launch --location=vsplit "tty-clock -C 4" 

#enabled layouts
enabled_layouts splits:split_axis=horizontal


env BLK=d0 
env CHR=0e 
env DIR=18 
env EXE=1c 
env REG=00 
env HARDLINK=02
env SYMLINK=24 
env MISSING=00 
env ORPHAN=09 
env FIFO=06 
env SOCK=5e 
env OTHER=21
env NNN_FCOLORS=$BLK$CHR$DIR$EXE$REG$HARDLINK$SYMLINK$MISSING$ORPHAN$FIFO$SOCK$OTHER
env NNN_PLUG=p:preview-tui

# borders
active_border_color #1f4f88
inactive_border_color #2a2a2f

draw_minimal_borders no
window_padding_width 0
window_border_width 1.4pt
window_margin_width -1

# [ Colors ] #

background #202222
foreground #e7e3dc

# Theme (Tomorrow Night Bright)
# black:   
color0 #665c54

# red:     

color1 #cc241d
# green:   
color2 #98971a
# yellow:  
color3 #ffaf00
# blue:    
color4 #2f6f90
# magenta: 
color5 #b16286
# cyan:    
color6 #689d6a
# white
color7 #fafaff
# Bright colors
# black:   
color8 #a8998c
# red:     
color9 #fb4934
# green:   
color10 #b8bb26
# yellow:  
color11 #fabf4f
# blue:    
color12 #83a598
# magenta: 
color13 #d3869b
# cyan:   
color14 #8ec07c
# white
color15 #fafaff
