# Finch's hyprland configuration.


# switched from i3 (since 2022) -> hyprland in 2026

# i3 for 4 years, and switching to this feels actually pretty nice
# lot of eyecandy for sure, less reliance on picom too which is cool.
# Turns out I fucking love wayland, things feel so much more smoooth.
# - finch.

# wiki link.
# https://wiki.hypr.land/Configuring/

# get ma keybinds + autostart
source = ~/.config/hypr/keybinds.conf
source = ~/.config/hypr/autostart.conf

# get the layout
source = ~/.config/hypr/layout.conf
source = ~/.config/hypr/monitor.conf
source = ~/.config/hypr/workspaces.conf

### ENVIRONMENT VARIABLES 
# See https://wiki.hypr.land/Configuring/Environment-variables/

env = XCURSOR_SIZE,24
env = HYPRCURSOR_SIZE,24
env = ELECTRON_OZONE_PLATFORM_HINT, wayland

### INPUT
# https://wiki.hypr.land/Configuring/Variables/#input

input {
    kb_layout = us
    kb_variant =
    kb_model =
    kb_options =
    kb_rules =

    follow_mouse = 1

    sensitivity = 0 # -1.0 - 1.0, 0 means no modification.

    touchpad {
        natural_scroll = false
    }
}

# See https://wiki.hypr.land/Configuring/Gestures
gesture = 3, horizontal, workspace

# Example per-device config
# See https://wiki.hypr.land/Configuring/Keywords/#per-device-input-configs for more
device {
    name = epic-mouse-v1
    sensitivity = -0.5
}

# execute this last...
# this fixes some xwayland shit that I completely forgot about.
exec-once= dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP 
