################
### MONITORS ###
################

# See https://wiki.hypr.land/Configuring/Monitors/ monitor=,preferred,auto,auto
monitor=DP-1,2560x1440@164,1920x-200,1
monitor=DP-2,preferred, 0x0, 1

